/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerClasesRouteImport } from './routes/verClases'
import { Route as CrearClaseRouteImport } from './routes/crearClase'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CancelarClaseRouteImport } from './routes/cancelarClase'
import { Route as IndexRouteImport } from './routes/index'

const VerClasesRoute = VerClasesRouteImport.update({
  id: '/verClases',
  path: '/verClases',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearClaseRoute = CrearClaseRouteImport.update({
  id: '/crearClase',
  path: '/crearClase',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelarClaseRoute = CancelarClaseRouteImport.update({
  id: '/cancelarClase',
  path: '/cancelarClase',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cancelarClase': typeof CancelarClaseRoute
  '/clientes': typeof ClientesRoute
  '/crearClase': typeof CrearClaseRoute
  '/verClases': typeof VerClasesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cancelarClase': typeof CancelarClaseRoute
  '/clientes': typeof ClientesRoute
  '/crearClase': typeof CrearClaseRoute
  '/verClases': typeof VerClasesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cancelarClase': typeof CancelarClaseRoute
  '/clientes': typeof ClientesRoute
  '/crearClase': typeof CrearClaseRoute
  '/verClases': typeof VerClasesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cancelarClase' | '/clientes' | '/crearClase' | '/verClases'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cancelarClase' | '/clientes' | '/crearClase' | '/verClases'
  id:
    | '__root__'
    | '/'
    | '/cancelarClase'
    | '/clientes'
    | '/crearClase'
    | '/verClases'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CancelarClaseRoute: typeof CancelarClaseRoute
  ClientesRoute: typeof ClientesRoute
  CrearClaseRoute: typeof CrearClaseRoute
  VerClasesRoute: typeof VerClasesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verClases': {
      id: '/verClases'
      path: '/verClases'
      fullPath: '/verClases'
      preLoaderRoute: typeof VerClasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crearClase': {
      id: '/crearClase'
      path: '/crearClase'
      fullPath: '/crearClase'
      preLoaderRoute: typeof CrearClaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancelarClase': {
      id: '/cancelarClase'
      path: '/cancelarClase'
      fullPath: '/cancelarClase'
      preLoaderRoute: typeof CancelarClaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CancelarClaseRoute: CancelarClaseRoute,
  ClientesRoute: ClientesRoute,
  CrearClaseRoute: CrearClaseRoute,
  VerClasesRoute: VerClasesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
