/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerInscriptosRouteImport } from './routes/verInscriptos'
import { Route as VerClasesRouteImport } from './routes/verClases'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as SolicitarTurnoRouteImport } from './routes/solicitarTurno'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as PagarClaseRouteImport } from './routes/pagarClase'
import { Route as ListaEsperaRouteImport } from './routes/listaEspera'
import { Route as IniciarSesionRouteImport } from './routes/iniciarSesion'
import { Route as CrearClaseRouteImport } from './routes/crearClase'
import { Route as ConfirmarTurnoRouteImport } from './routes/confirmar-turno'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as CancelarClaseRouteImport } from './routes/cancelarClase'
import { Route as CambiarProfesorRouteImport } from './routes/cambiarProfesor'
import { Route as CambiarPasswdRouteImport } from './routes/cambiarPasswd'
import { Route as IndexRouteImport } from './routes/index'

const VerInscriptosRoute = VerInscriptosRouteImport.update({
  id: '/verInscriptos',
  path: '/verInscriptos',
  getParentRoute: () => rootRouteImport,
} as any)
const VerClasesRoute = VerClasesRouteImport.update({
  id: '/verClases',
  path: '/verClases',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SolicitarTurnoRoute = SolicitarTurnoRouteImport.update({
  id: '/solicitarTurno',
  path: '/solicitarTurno',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const PagarClaseRoute = PagarClaseRouteImport.update({
  id: '/pagarClase',
  path: '/pagarClase',
  getParentRoute: () => rootRouteImport,
} as any)
const ListaEsperaRoute = ListaEsperaRouteImport.update({
  id: '/listaEspera',
  path: '/listaEspera',
  getParentRoute: () => rootRouteImport,
} as any)
const IniciarSesionRoute = IniciarSesionRouteImport.update({
  id: '/iniciarSesion',
  path: '/iniciarSesion',
  getParentRoute: () => rootRouteImport,
} as any)
const CrearClaseRoute = CrearClaseRouteImport.update({
  id: '/crearClase',
  path: '/crearClase',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmarTurnoRoute = ConfirmarTurnoRouteImport.update({
  id: '/confirmar-turno',
  path: '/confirmar-turno',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const CancelarClaseRoute = CancelarClaseRouteImport.update({
  id: '/cancelarClase',
  path: '/cancelarClase',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiarProfesorRoute = CambiarProfesorRouteImport.update({
  id: '/cambiarProfesor',
  path: '/cambiarProfesor',
  getParentRoute: () => rootRouteImport,
} as any)
const CambiarPasswdRoute = CambiarPasswdRouteImport.update({
  id: '/cambiarPasswd',
  path: '/cambiarPasswd',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cambiarPasswd': typeof CambiarPasswdRoute
  '/cambiarProfesor': typeof CambiarProfesorRoute
  '/cancelarClase': typeof CancelarClaseRoute
  '/clientes': typeof ClientesRoute
  '/confirmar-turno': typeof ConfirmarTurnoRoute
  '/crearClase': typeof CrearClaseRoute
  '/iniciarSesion': typeof IniciarSesionRoute
  '/listaEspera': typeof ListaEsperaRoute
  '/pagarClase': typeof PagarClaseRoute
  '/registro': typeof RegistroRoute
  '/solicitarTurno': typeof SolicitarTurnoRoute
  '/success': typeof SuccessRoute
  '/verClases': typeof VerClasesRoute
  '/verInscriptos': typeof VerInscriptosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cambiarPasswd': typeof CambiarPasswdRoute
  '/cambiarProfesor': typeof CambiarProfesorRoute
  '/cancelarClase': typeof CancelarClaseRoute
  '/clientes': typeof ClientesRoute
  '/confirmar-turno': typeof ConfirmarTurnoRoute
  '/crearClase': typeof CrearClaseRoute
  '/iniciarSesion': typeof IniciarSesionRoute
  '/listaEspera': typeof ListaEsperaRoute
  '/pagarClase': typeof PagarClaseRoute
  '/registro': typeof RegistroRoute
  '/solicitarTurno': typeof SolicitarTurnoRoute
  '/success': typeof SuccessRoute
  '/verClases': typeof VerClasesRoute
  '/verInscriptos': typeof VerInscriptosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cambiarPasswd': typeof CambiarPasswdRoute
  '/cambiarProfesor': typeof CambiarProfesorRoute
  '/cancelarClase': typeof CancelarClaseRoute
  '/clientes': typeof ClientesRoute
  '/confirmar-turno': typeof ConfirmarTurnoRoute
  '/crearClase': typeof CrearClaseRoute
  '/iniciarSesion': typeof IniciarSesionRoute
  '/listaEspera': typeof ListaEsperaRoute
  '/pagarClase': typeof PagarClaseRoute
  '/registro': typeof RegistroRoute
  '/solicitarTurno': typeof SolicitarTurnoRoute
  '/success': typeof SuccessRoute
  '/verClases': typeof VerClasesRoute
  '/verInscriptos': typeof VerInscriptosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cambiarPasswd'
    | '/cambiarProfesor'
    | '/cancelarClase'
    | '/clientes'
    | '/confirmar-turno'
    | '/crearClase'
    | '/iniciarSesion'
    | '/listaEspera'
    | '/pagarClase'
    | '/registro'
    | '/solicitarTurno'
    | '/success'
    | '/verClases'
    | '/verInscriptos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cambiarPasswd'
    | '/cambiarProfesor'
    | '/cancelarClase'
    | '/clientes'
    | '/confirmar-turno'
    | '/crearClase'
    | '/iniciarSesion'
    | '/listaEspera'
    | '/pagarClase'
    | '/registro'
    | '/solicitarTurno'
    | '/success'
    | '/verClases'
    | '/verInscriptos'
  id:
    | '__root__'
    | '/'
    | '/cambiarPasswd'
    | '/cambiarProfesor'
    | '/cancelarClase'
    | '/clientes'
    | '/confirmar-turno'
    | '/crearClase'
    | '/iniciarSesion'
    | '/listaEspera'
    | '/pagarClase'
    | '/registro'
    | '/solicitarTurno'
    | '/success'
    | '/verClases'
    | '/verInscriptos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CambiarPasswdRoute: typeof CambiarPasswdRoute
  CambiarProfesorRoute: typeof CambiarProfesorRoute
  CancelarClaseRoute: typeof CancelarClaseRoute
  ClientesRoute: typeof ClientesRoute
  ConfirmarTurnoRoute: typeof ConfirmarTurnoRoute
  CrearClaseRoute: typeof CrearClaseRoute
  IniciarSesionRoute: typeof IniciarSesionRoute
  ListaEsperaRoute: typeof ListaEsperaRoute
  PagarClaseRoute: typeof PagarClaseRoute
  RegistroRoute: typeof RegistroRoute
  SolicitarTurnoRoute: typeof SolicitarTurnoRoute
  SuccessRoute: typeof SuccessRoute
  VerClasesRoute: typeof VerClasesRoute
  VerInscriptosRoute: typeof VerInscriptosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verInscriptos': {
      id: '/verInscriptos'
      path: '/verInscriptos'
      fullPath: '/verInscriptos'
      preLoaderRoute: typeof VerInscriptosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verClases': {
      id: '/verClases'
      path: '/verClases'
      fullPath: '/verClases'
      preLoaderRoute: typeof VerClasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solicitarTurno': {
      id: '/solicitarTurno'
      path: '/solicitarTurno'
      fullPath: '/solicitarTurno'
      preLoaderRoute: typeof SolicitarTurnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagarClase': {
      id: '/pagarClase'
      path: '/pagarClase'
      fullPath: '/pagarClase'
      preLoaderRoute: typeof PagarClaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listaEspera': {
      id: '/listaEspera'
      path: '/listaEspera'
      fullPath: '/listaEspera'
      preLoaderRoute: typeof ListaEsperaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iniciarSesion': {
      id: '/iniciarSesion'
      path: '/iniciarSesion'
      fullPath: '/iniciarSesion'
      preLoaderRoute: typeof IniciarSesionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crearClase': {
      id: '/crearClase'
      path: '/crearClase'
      fullPath: '/crearClase'
      preLoaderRoute: typeof CrearClaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmar-turno': {
      id: '/confirmar-turno'
      path: '/confirmar-turno'
      fullPath: '/confirmar-turno'
      preLoaderRoute: typeof ConfirmarTurnoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancelarClase': {
      id: '/cancelarClase'
      path: '/cancelarClase'
      fullPath: '/cancelarClase'
      preLoaderRoute: typeof CancelarClaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambiarProfesor': {
      id: '/cambiarProfesor'
      path: '/cambiarProfesor'
      fullPath: '/cambiarProfesor'
      preLoaderRoute: typeof CambiarProfesorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cambiarPasswd': {
      id: '/cambiarPasswd'
      path: '/cambiarPasswd'
      fullPath: '/cambiarPasswd'
      preLoaderRoute: typeof CambiarPasswdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CambiarPasswdRoute: CambiarPasswdRoute,
  CambiarProfesorRoute: CambiarProfesorRoute,
  CancelarClaseRoute: CancelarClaseRoute,
  ClientesRoute: ClientesRoute,
  ConfirmarTurnoRoute: ConfirmarTurnoRoute,
  CrearClaseRoute: CrearClaseRoute,
  IniciarSesionRoute: IniciarSesionRoute,
  ListaEsperaRoute: ListaEsperaRoute,
  PagarClaseRoute: PagarClaseRoute,
  RegistroRoute: RegistroRoute,
  SolicitarTurnoRoute: SolicitarTurnoRoute,
  SuccessRoute: SuccessRoute,
  VerClasesRoute: VerClasesRoute,
  VerInscriptosRoute: VerInscriptosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
